### ISSUE TITLE
addfarmer page, contribute dropdown box is not visible

### ISSUE THREAD

**Issue by novialim** [novialim/farmily#104]
https://farmily.herokuapp.com/addfarmer -> click contribute (unable to link) and drop down box not visible

**Comment by jhuynh85** [comment]
Maybe increase the z-index of the dropdown box?

**Comment by novialim** [comment]
z-index:99 added id="addpages" class="dropdown-content", ineffective.

the user can see drop down and it disappears.

**Comment by novialim** [comment]
Commented out 

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="js/materialize.min.js"></script>

from head.handlebars for now.
