### ISSUE TITLE
Handlebars template of html

### ISSUE THREAD

**Issue by Goosetaculous** [novialim/farmily#33]
Analyze the html pages and determine a handlebar template layout

**Comment by jhuynh85** [comment]
Handlebars files and folders added in PR #40. The module still needs to be loaded in `server.js`

**Comment by jhuynh85** [comment]
Dupe of #47, #48, #49

**Comment by jhuynh85** [comment]
- [x] index
- [x] explore
- [x] addfarmer
- [x] allfarmer
- [ ] addreview
- [ ] contribute
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by jhuynh85** [comment]
@novialim Are there any pages we're missing? I'm not up-to-date on which pages we want to convert to handlebars

**Comment by novialim** [comment]
updated your comment and I will double check everything Friday evening. (WHEN WE STOP CODING!!)
